---
changelog:
  exclude:
    labels:
      - ignore-for-release
      - duplicate
      - invalid
      - question
      - wontfix
    # authors:
    #   - 
  categories:
    - title: Bug Fix 🛠
      labels:
        - Semver-Patch
        - bug
    - title: Security Fix 🛠
      labels:
        - Semver-Patch
        - security fix
    - title: Exciting New Features 🎉
      labels:
        - Semver-Major
        - enhancement
    - title: Exciting New Features 🎉
      labels:
        - Semver-Minor
        - enhancement
    - title: Other Changes
      labels:
        - "*"
...

# changelog.exclude.labels                A list of labels that exclude a pull request from appearing in release notes
# changelog.exclude.authors               A list of user or bot login handles whose pull requests are to be excluded from release notes.
# changelog.categories[*].title           Required. The title of a category of changes in release notes.
# changelog.categories[*].labels          Required. Labels that qualify a pull request for this category. Use * as a catch-all for pull requests that didn't match any of the previous categories.
# changelog.categories[*].exclude.labels  A list of labels that exclude a pull request from appearing in this category.
# changelog.categories[*].exclude.authors A list of user or bot login handles whose pull requests are to be excluded from this category.

# Labels
# Semver-Major        semantic major version
# Semver-Minor        enhancement or addition to existing functionality
# Semver-Patch        security or bug fix
# enhancement         New feature or request
# security fix        Cyber would like this done
# bug                 Something isn't working
# ignore-for-release  internal notes
# documentation       Improvements or additions to documentation
# duplicate           This issue or pull request already exists
# good first issue    Good for newcomers
# help wanted         Extra attention is needed
# invalid             This doesn't seem right
# question            Further information is requested
# wontfix             This will not be worked on